apiVersion: v1
kind: Service
metadata:
  name: at-devcalc-api-service
  namespace: at-devcalc-api
spec:
  type: ClusterIP
  selector:
    app: at-devcalc-api-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP